spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autosinistre
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: a60402b4cd00003f347f5fa9e009f807659a19cfa4a9dc2c80a2eaedc7d67075
  expiration: 86400000

cors:
  allowed-origins: http://localhost:5173